#!/usr/bin/env bash
# install.sh — self-contained, hardened installer for agy-delegate (Option D).
#
# The USER runs this in their real terminal (zero ctx_shell/Bash allowlist
# constraints). It installs two launcher wrappers into ~/.local/bin:
#   - agy-bridge : execs this plugin's scripts/agy_bridge.sh
#   - gemini     : execs this plugin's scripts/gemini_shim.sh (drop-in shim)
#
# SECURITY MODEL
#   - Wrappers exec a PINNED ABSOLUTE PATH recorded at install time. They do NOT
#     glob ~/.claude/plugins/cache (user-writable = exec-hijack) and do NOT call
#     `claude plugin list` per invocation. If the pinned target vanishes (plugin
#     updated/moved) the wrapper FAILS LOUD and tells the user to re-run install.
#   - refuse-root; set -euo pipefail; every expansion quoted; [[ ]] not [ ].
#   - writes ONLY under ~/.local/bin, ~ (rc backups), ~/.config/agy-delegate,
#     ~/.gemini. NEVER touches the repo.
#
# Env flags (opt-in, default off):
#   AGY_SETUP_REGISTER_TOKENSAVE=1  register tokensave as an agy MCP server
#   AGY_SETUP_PATCH_ALIASES=1       apply the recursive-gemini rc alias patch
#
# Override the installer's self-resolved plugin dir (used by tests / manual
# installs from a clone) with AGY_PLUGIN_DIR=/abs/path/to/plugin-root.

set -euo pipefail

WRAPPER_MARKER='# agy-delegate-wrapper'

# ── refuse root ──────────────────────────────────────────────────────────────
if [[ "${EUID:-$(id -u)}" -eq 0 || -n "${SUDO_USER:-}" ]]; then
    echo "ERROR: refusing to run as root (or via sudo). Run as your normal user." >&2
    exit 1
fi

# ── resolve this plugin's root (dir containing scripts/) ─────────────────────
if [[ -n "${AGY_PLUGIN_DIR:-}" ]]; then
    PLUGIN_DIR="$AGY_PLUGIN_DIR"
else
    _self="$(readlink -f "${BASH_SOURCE[0]}")"
    PLUGIN_DIR="$(cd "$(dirname "$_self")/.." && pwd)"
fi
BRIDGE_TARGET="$PLUGIN_DIR/scripts/agy_bridge.sh"
SHIM_TARGET="$PLUGIN_DIR/scripts/gemini_shim.sh"

if [[ ! -f "$BRIDGE_TARGET" || ! -f "$SHIM_TARGET" ]]; then
    echo "ERROR: could not locate plugin scripts under '$PLUGIN_DIR/scripts'." >&2
    echo "       Set AGY_PLUGIN_DIR to the agy-delegate plugin root and re-run." >&2
    exit 1
fi

BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

_ts() { date +%Y%m%d%H%M%S; }

# is_our_wrapper PATH -> 0 if the file exists and carries our signature marker.
is_our_wrapper() {
    local f="$1"
    [[ -f "$f" ]] && grep -qF "$WRAPPER_MARKER" "$f"
}

# write_wrapper NAME PINNED_TARGET DEST
# Emits a pinned-path launcher: fail-loud on missing target, validate regular
# file, exec -a sets the launcher argv0; the shim resolves its own path via BASH_SOURCE. NO cache glob, NO per-call claude list.
# The exec target is always the pinned literal above; the newer-sibling check
# below only ever WARNS on stderr, it never feeds the exec path.
write_wrapper() {
    local name="$1" target="$2" dest="$3"
    # Non-clobber: back up a pre-existing NON-agy file at dest.
    if [[ -e "$dest" || -L "$dest" ]] && ! is_our_wrapper "$dest"; then
        local bak
        bak="$dest.bak-agy-$(_ts)"
        cp -Pf "$dest" "$bak"
        echo "WARNING: '$dest' already exists and is not an agy-delegate wrapper." >&2
        echo "         Backed it up to '$bak' before overwriting." >&2
    fi
    # Derive the pinned version dir's own basename and its parent (the
    # versions root, e.g. .../agy-delegate/agy-delegate/) so the generated
    # wrapper can warn (stderr only) if a newer sibling version directory
    # shows up there after `claude plugin update`. Both are install-time
    # literals baked into the heredoc below, same as _AGY_TARGET.
    local scripts_dir version_dir version parent_dir
    scripts_dir="${target%/*}"
    version_dir="${scripts_dir%/*}"
    version="${version_dir##*/}"
    parent_dir="${version_dir%/*}"
    local tmp
    tmp="$(mktemp "$dest.agy-tmp.XXXXXX")"
    cat > "$tmp" <<WRAP
#!/usr/bin/env bash
$WRAPPER_MARKER
# Pinned launcher for agy-delegate '$name'. Generated by install.sh — do not edit.
# Execs a PINNED ABSOLUTE PATH; fails loud if the plugin moved/was updated.
set -euo pipefail
_AGY_TARGET='$target'
_AGY_VERSION='$version'
_AGY_VERSIONS_ROOT='$parent_dir'
if [[ ! -f "\$_AGY_TARGET" ]]; then
    echo "ERROR: agy-delegate moved or was updated; '\$_AGY_TARGET' is gone." >&2
    echo "       Re-run the install one-liner (see /agy-setup) to repin it." >&2
    exit 127
fi
# Newer-sibling check: warn only, never changes what gets exec'd. Only runs
# when the pinned version dir's own name looks like a version (skips dev/test
# installs where the plugin root isn't under a versioned cache layout).
if [[ "\$_AGY_VERSION" =~ ^[0-9]+(\.[0-9]+)*\$ ]]; then
    for _agy_sibling in "\$_AGY_VERSIONS_ROOT"/*/; do
        [[ -d "\$_agy_sibling" ]] || continue
        _agy_sibling_ver="\${_agy_sibling%/}"
        _agy_sibling_ver="\${_agy_sibling_ver##*/}"
        [[ "\$_agy_sibling_ver" =~ ^[0-9]+(\.[0-9]+)*\$ ]] || continue
        [[ "\$_agy_sibling_ver" == "\$_AGY_VERSION" ]] && continue
        if [[ "\$(printf '%s\n' "\$_agy_sibling_ver" "\$_AGY_VERSION" | sort -V | tail -n1)" == "\$_agy_sibling_ver" ]]; then
            echo "WARNING: agy-delegate \$_AGY_VERSION is pinned but a newer version '\$_agy_sibling_ver' is also installed in '\$_AGY_VERSIONS_ROOT'." >&2
            echo "         Still running the pinned \$_AGY_VERSION copy. Re-run the install one-liner (see /agy-setup) to repin \$_agy_sibling_ver." >&2
        fi
    done
fi
exec -a "$name" bash "\$_AGY_TARGET" "\$@"
WRAP
    chmod +x "$tmp"
    chmod +x "$target" 2>/dev/null || true
    mv -f "$tmp" "$dest"
    echo "Installed '$name' -> $target"
}

echo "== agy-delegate installer =="
echo "Plugin root: $PLUGIN_DIR"

# ── full-$PATH shadow scan (before writing the gemini wrapper) ───────────────
_real_gemini=""
IFS=':' read -r -a _path_parts <<< "${PATH:-}"
for _d in "${_path_parts[@]}"; do
    [[ -z "$_d" ]] && continue
    [[ "$_d" == "$BIN_DIR" ]] && continue
    _cand="$_d/gemini"
    if [[ -x "$_cand" && ! -d "$_cand" ]] && ! is_our_wrapper "$_cand"; then
        _real_gemini="$_cand"
        break
    fi
done
if [[ -n "$_real_gemini" ]]; then
    echo "WARNING: a real 'gemini' exists at '$_real_gemini'." >&2
    echo "         The agy shim in '$BIN_DIR/gemini' will SHADOW it for every PATH caller." >&2
fi

# ── write the two pinned wrappers ────────────────────────────────────────────
write_wrapper "agy-bridge" "$BRIDGE_TARGET" "$BIN_DIR/agy-bridge"
write_wrapper "gemini" "$SHIM_TARGET" "$BIN_DIR/gemini"

# ── shadow disclosure notice ─────────────────────────────────────────────────
echo
echo "NOTICE: '$BIN_DIR/gemini' now shadows the 'gemini' command for ALL callers"
echo "        whose PATH includes '$BIN_DIR' before any real gemini install."
echo "        Blast radius: every tool that runs 'gemini' (Claude Octopus,"
echo "        Metaswarm, your interactive shell) will invoke agy instead."
echo "        To undo: run scripts/uninstall.sh (removes only our wrappers and"
echo "        restores any backed-up original)."

# ── PATH-in-place check ──────────────────────────────────────────────────────
if [[ ":${PATH:-}:" == *":$BIN_DIR:"* ]]; then
    echo "PATH contains '$BIN_DIR' — good."
else
    echo "WARNING: '$BIN_DIR' is not in PATH. Add it for your shell:" >&2
    echo "  bash/zsh:  export PATH=\"\$HOME/.local/bin:\$PATH\"  (add to your rc file)" >&2
    echo "  fish:      fish_add_path ~/.local/bin" >&2
fi

# ── consent-gated recursive-gemini rc alias patch (dry-run unless flag) ───────
if [[ -n "$_real_gemini" ]]; then
    for RC in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.bash_aliases"; do
        [[ -f "$RC" ]] || continue
        if grep -qE "^alias gemini='[^']* gemini'\$" "$RC" 2>/dev/null; then
            old_line="$(grep "^alias gemini=" "$RC" || true)"
            echo "Recursive 'gemini' alias found in $RC:"
            echo "  $old_line"
            if [[ "${AGY_SETUP_PATCH_ALIASES:-0}" != "1" ]]; then
                echo "  (dry-run) set AGY_SETUP_PATCH_ALIASES=1 to rewrite it to call $_real_gemini."
                continue
            fi
            cp -f "$RC" "$RC.bak-agy-$(_ts)"
            python3 - "$RC" "$_real_gemini" <<'PY'
import re, sys
rc, real = sys.argv[1], sys.argv[2]
txt = open(rc).read()
out = re.sub(r"^(alias gemini='.*) gemini'$",
             lambda m: m.group(1) + ' ' + real + "'", txt, flags=re.M)
open(rc, 'w').write(out)
PY
            echo "Patched $RC (backup written)."
        fi
    done
fi

# ── opt-in: register tokensave as an agy MCP server + availability hint ──────
AGY_MCP_CFG="$HOME/.gemini/antigravity-cli/mcp_config.json"
HINT_DIR="$HOME/.config/agy-delegate"
HINT="$HINT_DIR/config.json"
TOKENSAVE_BIN="$(command -v tokensave 2>/dev/null || echo "$HOME/.local/bin/tokensave")"

AGY_HAS_LEANCTX=0
AGY_HAS_TOKENSAVE=0
_agy_detect() {
    if ! command -v python3 >/dev/null 2>&1; then
        echo "0 0"
        return 0
    fi
    python3 - "$AGY_MCP_CFG" <<'PY'
import sys, json, os
p = sys.argv[1]; lc = ts = False
if os.path.exists(p):
    try:
        s = json.load(open(p)).get('mcpServers', {})
        lc = 'lean-ctx' in s; ts = 'tokensave' in s
    except Exception:
        pass
print(f"{int(lc)} {int(ts)}")
PY
}
read -r AGY_HAS_LEANCTX AGY_HAS_TOKENSAVE < <(_agy_detect)

_register_tokensave() {
    if ! command -v python3 >/dev/null 2>&1; then
        echo "WARNING: python3 not found — skipping tokensave registration (fail-open)." >&2
        return 0
    fi
    if [[ ! -f "$AGY_MCP_CFG" ]]; then
        echo "WARNING: agy mcp_config not found at '$AGY_MCP_CFG' — is agy initialised? Skipping." >&2
        return 0
    fi
    # Re-read the config IMMEDIATELY before the write (minimize TOCTOU).
    python3 - "$AGY_MCP_CFG" "$TOKENSAVE_BIN" <<'PY'
import sys, json, os, hashlib, tempfile, time
cfg, tsbin = sys.argv[1], sys.argv[2]
raw = open(cfg, 'rb').read()
try:
    d = json.loads(raw)
except Exception as e:
    print(f"ERROR: agy mcp_config is not valid JSON ({e}); refusing to overwrite a "
          f"recoverable config. Aborting.", file=sys.stderr)
    sys.exit(3)
srv = d.setdefault('mcpServers', {})
if 'tokensave' in srv:
    print("tokensave already registered for agy — no change.")
    sys.exit(0)
bak = cfg + '.bak-agy-' + time.strftime('%Y%m%d%H%M%S')
open(bak, 'wb').write(raw)
if (hashlib.sha256(open(bak, 'rb').read()).hexdigest()
        != hashlib.sha256(raw).hexdigest()) or os.path.getsize(bak) != len(raw):
    print(f"ERROR: backup verification failed for {bak}; aborting without modifying "
          f"{cfg}.", file=sys.stderr)
    sys.exit(4)
srv['tokensave'] = {"command": tsbin, "args": ["serve"]}
dirn = os.path.dirname(cfg) or '.'
fd, tmp = tempfile.mkstemp(prefix='.mcp_config.', dir=dirn)
os.close(fd); os.chmod(tmp, 0o600)
try:
    with open(tmp, 'w') as f:
        json.dump(d, f, indent=2); f.write('\n')
    json.load(open(tmp))
except Exception as e:
    os.unlink(tmp)
    print(f"ERROR: wrote invalid JSON temp ({e}); removed temp, {cfg} unchanged. "
          f"Backup at {bak}.", file=sys.stderr)
    sys.exit(5)
os.replace(tmp, cfg)
print(f"Registered tokensave for agy (backup: {bak}).")
PY
}

if [[ -x "$TOKENSAVE_BIN" && "$AGY_HAS_TOKENSAVE" == "0" ]]; then
    DO_REG="${AGY_SETUP_REGISTER_TOKENSAVE:-}"
    if [[ -z "$DO_REG" ]]; then
        if [[ -t 0 ]]; then
            read -rp "Register tokensave as an agy MCP server? Grants agy code-graph READ + local-project MUTATE tools. [y/N] " ans
            [[ "$ans" =~ ^[Yy]$ ]] && DO_REG=1 || DO_REG=0
        else
            echo "tokensave is available but not registered for agy. Re-run with" \
                 "AGY_SETUP_REGISTER_TOKENSAVE=1 to register. Skipping."
            DO_REG=0
        fi
    fi
    if [[ "$DO_REG" == "1" ]]; then
        if _register_tokensave; then
            read -r AGY_HAS_LEANCTX AGY_HAS_TOKENSAVE < <(_agy_detect)
        else
            echo "tokensave registration did not complete (see error above); your" \
                 "existing config is unchanged." >&2
        fi
    fi
fi

# ── write MCP availability hint (tokensave:false on decline) ──────────────────
mkdir -p "$HINT_DIR"
if command -v python3 >/dev/null 2>&1; then
    python3 - "$HINT" "$AGY_HAS_LEANCTX" "$AGY_HAS_TOKENSAVE" <<'PY'
import sys, json
p, lc, ts = sys.argv[1], sys.argv[2] == '1', sys.argv[3] == '1'
json.dump({"lean_ctx": lc, "tokensave": ts}, open(p, 'w'), indent=2)
open(p, 'a').write('\n')
print(f"Wrote MCP availability hint {p}: lean_ctx={lc} tokensave={ts}")
PY
fi

# ── final LIVE verify (non-fatal) ────────────────────────────────────────────
echo
echo "== live verify (non-fatal) =="
if "$BIN_DIR/agy-bridge" --types >/dev/null 2>&1; then
    echo "agy-bridge --types: ok"
else
    echo "agy-bridge --types: could not run (agy may not be installed/authed yet)."
fi
if printf 'Say only: shim ok\n' | "$BIN_DIR/gemini" -m gemini-2.5-flash -o text --approval-mode yolo >/dev/null 2>&1; then
    echo "gemini shim smoke: ok"
else
    echo "gemini shim smoke: could not run (agy may not be installed/authed yet)."
fi

echo
echo "Done. If '$BIN_DIR' is on your PATH, 'agy-bridge' and 'gemini' are ready."
